/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "romanmath.check" instead.
 */

#include <check.h>

#line 1 "romanmath.check"
#include "romanmath.h"

START_TEST(aTest)
{
#line 4
	ck_assert_int_eq( 1, 1 );

}
END_TEST

START_TEST(convertRoman)
{
#line 7
	ck_assert_int_eq( romanToInt("I"), 1);
	ck_assert_int_eq( romanToInt("II"), 2);
	ck_assert_int_eq( romanToInt("III"), 3);
	ck_assert_int_eq( romanToInt("IV"), 4);
	ck_assert_int_eq( romanToInt("V"), 5);
	ck_assert_int_eq( romanToInt("VI"), 6);
	ck_assert_int_eq( romanToInt("VII"), 7);
	ck_assert_int_eq( romanToInt("VIII"), 8);
	ck_assert_int_eq( romanToInt("IX"), 9);
	ck_assert_int_eq( romanToInt("X"), 10);
	ck_assert_int_eq( romanToInt("L"), 50);
	ck_assert_int_eq( romanToInt("C"), 100);
	ck_assert_int_eq( romanToInt("D"), 500);
	ck_assert_int_eq( romanToInt("M"), 1000);
	ck_assert_int_eq( romanToInt("MMDXVI"), 2516);

}
END_TEST

START_TEST(convertRomanInvalids)
{
#line 24
	ck_assert_int_eq( romanToInt("IIII"), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt("VVV"), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt("VV"), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt("XXXX"), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt("LL"), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt("CCCC"), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt("DD"), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt("MMMMM"), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt(""), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt("W"), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt("WII"), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt("VX"), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt("VL"), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt("VD"), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt("VM"), INVALID_ROMAN_NUMERAL);
	ck_assert_int_eq( romanToInt(""), INVALID_ROMAN_NUMERAL);


}
END_TEST

START_TEST(sumRomanNumeralsInt)
{
#line 43
	ck_assert_int_eq( romanSumInt("I", "I"), 2);
	ck_assert_int_eq( romanSumInt("XIV", "LX"), 74);

}
END_TEST

START_TEST(sumRomanNumerals)
{
#line 47
	ck_assert_str_eq( romanSum("I", "I"), "II");
	ck_assert_str_eq( romanSum("XIV", "LX"), "LXXIV");


}
END_TEST

START_TEST(subtractRomanNumerals)
{
#line 52
	ck_assert_str_eq( romanSubtract("II", "I"), "I");
	ck_assert_str_eq( romanSubtract("LXXIV", "LX"), "XIV");
	ck_assert_ptr_eq( romanSubtract("I", "I"), 0);

}
END_TEST

START_TEST(convertIntToRoman)
{
#line 57
	ck_assert_str_eq( intToRoman(1), "I");
	ck_assert_str_eq( intToRoman(2), "II");
	ck_assert_str_eq( intToRoman(3), "III");
	ck_assert_str_eq( intToRoman(4), "IV");
	ck_assert_str_eq( intToRoman(5), "V");
	ck_assert_str_eq( intToRoman(6), "VI");
	ck_assert_str_eq( intToRoman(7), "VII");
	ck_assert_str_eq( intToRoman(8), "VIII");
	ck_assert_str_eq( intToRoman(9), "IX");
	ck_assert_str_eq( intToRoman(10), "X");
	ck_assert_str_eq( intToRoman(11), "XI");
	ck_assert_str_eq( intToRoman(21), "XXI");
	ck_assert_str_eq( intToRoman(31), "XXXI");
	ck_assert_str_eq( intToRoman(41), "XLI");
	ck_assert_str_eq( intToRoman(49), "XLIX");
	ck_assert_str_eq( intToRoman(50), "L");
	ck_assert_str_eq( intToRoman(90), "XC");
	ck_assert_str_eq( intToRoman(100), "C");
	ck_assert_str_eq( intToRoman(400), "CD");
	ck_assert_str_eq( intToRoman(500), "D");
	ck_assert_str_eq( intToRoman(900), "CM");
	ck_assert_str_eq( intToRoman(1000), "M");
	ck_assert_str_eq( intToRoman(2516), "MMDXVI");

}
END_TEST

START_TEST(checkInvalidValues)
{
#line 82
	ck_assert_ptr_eq( intToRoman(6000), 0);


}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, aTest);
    tcase_add_test(tc1_1, convertRoman);
    tcase_add_test(tc1_1, convertRomanInvalids);
    tcase_add_test(tc1_1, sumRomanNumeralsInt);
    tcase_add_test(tc1_1, sumRomanNumerals);
    tcase_add_test(tc1_1, subtractRomanNumerals);
    tcase_add_test(tc1_1, convertIntToRoman);
    tcase_add_test(tc1_1, checkInvalidValues);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
